[2020-05-14 22:21:36,670] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-14 22:22:01,761] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 302 0
[2020-05-14 22:22:01,783] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET / HTTP/1.1" 500 59
[2020-05-14 22:22:01,834] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2944
[2020-05-14 22:22:01,835] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /login/ HTTP/1.1" 500 59
[2020-05-14 22:22:01,895] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/css/font.css HTTP/1.1" 200 505
[2020-05-14 22:22:01,929] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/layui.js HTTP/1.1" 200 6667
[2020-05-14 22:22:01,933] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/css/xadmin.css HTTP/1.1" 200 9946
[2020-05-14 22:22:01,943] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/css/login.css HTTP/1.1" 200 2268
[2020-05-14 22:22:01,954] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/js/jquery-3.2.1.min.js HTTP/1.1" 200 86659
[2020-05-14 22:22:01,966] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/css/layui.css HTTP/1.1" 200 89020
[2020-05-14 22:22:01,980] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/js/jquery.cookie.js HTTP/1.1" 200 3121
[2020-05-14 22:22:02,020] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/js/flow-meter.js HTTP/1.1" 200 1879
[2020-05-14 22:22:02,041] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/images/bg.png HTTP/1.1" 200 28211
[2020-05-14 22:22:02,054] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/images/aiwrap.png HTTP/1.1" 200 3032
[2020-05-14 22:22:02,064] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/lay/modules/form.js HTTP/1.1" 200 9259
[2020-05-14 22:22:02,074] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/lay/modules/layer.js HTTP/1.1" 200 22041
[2020-05-14 22:22:02,092] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/css/modules/layer/default/layer.css?v=3.1.1 HTTP/1.1" 200 14425
[2020-05-14 22:22:02,099] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 302 0
[2020-05-14 22:22:02,100] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 59
[2020-05-14 22:22:02,109] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2944
[2020-05-14 22:22:02,111] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /login/ HTTP/1.1" 500 59
[2020-05-14 22:22:05,703] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/login/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 552, in connect
    sock = self._connect()
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 609, in _connect
    raise err
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 597, in _connect
    sock.connect(socket_address)
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\log.py", line 52, in process_request
    action_type = LogMiddleware.__render_action_type_str(action, params)
  File "D:\project\python\flowmeter\flowmeter\middlewares\log.py", line 26, in __render_action_type_str
    log_dict_str = conf_cache_api.get_hash('log_configure', action)
  File "D:\project\python\flowmeter\flowmeter\config\api\cache.py", line 155, in get_hash
    val = conn.hget(name, key)
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\client.py", line 2975, in hget
    return self.execute_command('HGET', name, key)
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\client.py", line 875, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 1185, in get_connection
    connection.connect()
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 557, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10049 connecting to 0.0.0.0:6379. 在其上下文中，该请求的地址无效。.
[2020-05-14 22:22:05,705] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /handler/login/ HTTP/1.1" 500 21246
[2020-05-14 22:22:05,708] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /handler/login/ HTTP/1.1" 500 59
[2020-05-14 22:22:05,715] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/css/modules/layer/default/icon.png HTTP/1.1" 200 11493
[2020-05-14 22:25:10,795] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-14 22:25:16,132] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/login/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 552, in connect
    sock = self._connect()
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 609, in _connect
    raise err
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 597, in _connect
    sock.connect(socket_address)
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\log.py", line 52, in process_request
    action_type = LogMiddleware.__render_action_type_str(action, params)
  File "D:\project\python\flowmeter\flowmeter\middlewares\log.py", line 26, in __render_action_type_str
    log_dict_str = conf_cache_api.get_hash('log_configure', action)
  File "D:\project\python\flowmeter\flowmeter\config\api\cache.py", line 155, in get_hash
    val = conn.hget(name, key)
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\client.py", line 2975, in hget
    return self.execute_command('HGET', name, key)
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\client.py", line 875, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 1185, in get_connection
    connection.connect()
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 557, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10049 connecting to 0.0.0.0:6379. 在其上下文中，该请求的地址无效。.
[2020-05-14 22:25:16,134] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /handler/login/ HTTP/1.1" 500 21246
[2020-05-14 22:25:16,138] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /handler/login/ HTTP/1.1" 500 59
[2020-05-14 22:25:18,150] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2944
[2020-05-14 22:25:18,151] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /login/ HTTP/1.1" 500 59
[2020-05-14 22:25:18,185] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 302 0
[2020-05-14 22:25:18,186] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 59
[2020-05-14 22:25:18,192] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2944
[2020-05-14 22:25:18,193] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /login/ HTTP/1.1" 500 59
[2020-05-14 22:25:21,524] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/login/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 552, in connect
    sock = self._connect()
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 609, in _connect
    raise err
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 597, in _connect
    sock.connect(socket_address)
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\log.py", line 52, in process_request
    action_type = LogMiddleware.__render_action_type_str(action, params)
  File "D:\project\python\flowmeter\flowmeter\middlewares\log.py", line 26, in __render_action_type_str
    log_dict_str = conf_cache_api.get_hash('log_configure', action)
  File "D:\project\python\flowmeter\flowmeter\config\api\cache.py", line 155, in get_hash
    val = conn.hget(name, key)
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\client.py", line 2975, in hget
    return self.execute_command('HGET', name, key)
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\client.py", line 875, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 1185, in get_connection
    connection.connect()
  File "D:\project\python\flowmeter\venv\lib\site-packages\redis\connection.py", line 557, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10049 connecting to 0.0.0.0:6379. 在其上下文中，该请求的地址无效。.
[2020-05-14 22:25:21,525] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /handler/login/ HTTP/1.1" 500 21246
[2020-05-14 22:25:21,529] [basehttp.py:154] [basehttp:log_message] [ERROR]- "POST /handler/login/ HTTP/1.1" 500 59
[2020-05-14 22:26:32,498] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-14 22:26:35,886] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2944
[2020-05-14 22:26:35,891] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /login/ HTTP/1.1" 500 59
[2020-05-14 22:26:35,924] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 302 0
[2020-05-14 22:26:35,924] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 59
[2020-05-14 22:26:35,929] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2944
[2020-05-14 22:26:35,930] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /login/ HTTP/1.1" 500 59
[2020-05-14 22:26:39,103] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：login
[2020-05-14 22:26:39,130] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/login/ HTTP/1.1" 200 96
[2020-05-14 22:26:40,353] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index HTTP/1.1" 301 0
[2020-05-14 22:26:40,354] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /index HTTP/1.1" 500 59
[2020-05-14 22:26:40,467] [error_handler.py:24] [error_handler:process_exception] [ERROR]- Configure matching query does not exist.
[2020-05-14 22:26:40,469] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 109
[2020-05-14 22:26:40,518] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-05-14 22:26:40,519] [basehttp.py:154] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 3577
[2020-05-14 22:28:54,721] [error_handler.py:24] [error_handler:process_exception] [ERROR]- Configure matching query does not exist.
[2020-05-14 22:28:54,722] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 109
[2020-05-14 22:28:55,883] [error_handler.py:24] [error_handler:process_exception] [ERROR]- Configure matching query does not exist.
[2020-05-14 22:28:55,884] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 109
[2020-05-14 22:28:56,074] [error_handler.py:24] [error_handler:process_exception] [ERROR]- Configure matching query does not exist.
[2020-05-14 22:28:56,075] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 109
[2020-05-14 22:28:56,234] [error_handler.py:24] [error_handler:process_exception] [ERROR]- Configure matching query does not exist.
[2020-05-14 22:28:56,235] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 109
[2020-05-14 22:29:28,329] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-14 22:29:31,306] [error_handler.py:24] [error_handler:process_exception] [ERROR]- Configure matching query does not exist.
[2020-05-14 22:29:31,309] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 109
[2020-05-14 22:30:54,218] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 13321
[2020-05-14 22:30:54,241] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/js/xadmin.js HTTP/1.1" 200 16891
[2020-05-14 22:30:54,308] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/font/iconfont.woff?v=240 HTTP/1.1" 200 26744
[2020-05-14 22:30:54,325] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/fonts/iconfont.woff HTTP/1.1" 200 30200
[2020-05-14 22:30:54,330] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/lay/modules/element.js HTTP/1.1" 200 7264
[2020-05-14 22:30:54,336] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/dist/notice.js HTTP/1.1" 200 24421
[2020-05-14 22:30:54,352] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /statistic/admin/ HTTP/1.1" 200 3937
[2020-05-14 22:30:54,380] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/lay/modules/jquery.js HTTP/1.1" 200 97648
[2020-05-14 22:43:05,585] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 13321
[2020-05-14 22:43:05,631] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /statistic/admin/ HTTP/1.1" 200 3937
[2020-05-14 22:43:30,282] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 13321
[2020-05-14 22:43:30,322] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /statistic/admin/ HTTP/1.1" 200 3937
[2020-05-14 22:43:38,979] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 13321
[2020-05-14 22:43:39,012] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /statistic/admin/ HTTP/1.1" 200 3937
[2020-05-14 22:46:19,563] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 13328
[2020-05-14 22:46:19,608] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /statistic/admin/ HTTP/1.1" 200 3937
[2020-05-14 22:46:21,120] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 13328
[2020-05-14 22:46:21,166] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /statistic/admin/ HTTP/1.1" 200 3937
[2020-05-14 22:47:03,219] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 13314
[2020-05-14 22:47:03,263] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /statistic/admin/ HTTP/1.1" 200 3937
[2020-05-14 22:47:07,147] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /manufacturer/view/ HTTP/1.1" 200 11027
[2020-05-14 22:47:07,212] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/lay/modules/laydate.js HTTP/1.1" 200 27377
[2020-05-14 22:47:07,223] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/lay/modules/table.js HTTP/1.1" 200 30963
[2020-05-14 22:47:07,227] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/css/modules/laydate/default/laydate.css?v=5.0.9 HTTP/1.1" 200 7537
[2020-05-14 22:47:07,239] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/lay/modules/laytpl.js HTTP/1.1" 200 1836
[2020-05-14 22:47:07,259] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/lay/modules/laypage.js HTTP/1.1" 200 4472
[2020-05-14 22:47:07,279] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/lay/modules/util.js HTTP/1.1" 200 3458
[2020-05-14 22:47:07,307] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_manufacturer
[2020-05-14 22:47:07,326] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/manufacturer/?action=query_manufacturer&page=1&limit=10 HTTP/1.1" 200 1235
[2020-05-14 22:47:07,545] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu_user/view/ HTTP/1.1" 200 10316
[2020-05-14 22:47:07,608] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_dtu_user
[2020-05-14 22:47:07,613] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/dtu_user/?action=query_dtu_user&page=1&limit=10 HTTP/1.1" 200 239
[2020-05-14 22:47:07,898] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-05-14 22:47:07,924] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/lay/modules/tree.js HTTP/1.1" 200 3060
[2020-05-14 22:47:07,946] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-05-14 22:47:07,948] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-05-14 22:47:08,120] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /meter/view/ HTTP/1.1" 200 20643
[2020-05-14 22:47:08,180] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_meter
[2020-05-14 22:47:08,183] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_manufacturer
[2020-05-14 22:47:08,205] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/manufacturer/?param=%7B%7D&action=query_manufacturer HTTP/1.1" 200 1235
[2020-05-14 22:47:08,206] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/meter/?action=query_meter&page=1&limit=10 HTTP/1.1" 200 1232
[2020-05-14 22:47:08,702] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu/view/ HTTP/1.1" 200 8912
[2020-05-14 22:47:08,799] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_dtu
[2020-05-14 22:47:08,804] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_dtu_user_of_select_box
[2020-05-14 22:47:08,809] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_manufacturer
[2020-05-14 22:47:08,823] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/dtu_user/?param=%7B%7D&action=query_dtu_user_of_select_box HTTP/1.1" 200 116
[2020-05-14 22:47:08,827] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/dtu/?action=query_dtu&page=1&limit=10 HTTP/1.1" 200 1159
[2020-05-14 22:47:08,833] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/manufacturer/?param=%7B%7D&action=query_manufacturer HTTP/1.1" 200 1235
[2020-05-14 22:47:08,926] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /manufacturer/view/ HTTP/1.1" 200 11027
[2020-05-14 22:47:08,989] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_manufacturer
[2020-05-14 22:47:09,004] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/manufacturer/?action=query_manufacturer&page=1&limit=10 HTTP/1.1" 200 1235
[2020-05-14 22:47:09,127] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /manufacturer/view/ HTTP/1.1" 200 11027
[2020-05-14 22:47:09,189] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_manufacturer
[2020-05-14 22:47:09,207] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/manufacturer/?action=query_manufacturer&page=1&limit=10 HTTP/1.1" 200 1235
[2020-05-14 22:47:09,438] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/view/ HTTP/1.1" 200 10249
[2020-05-14 22:47:09,481] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_admin
[2020-05-14 22:47:09,488] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/admin/?action=query_admin&page=1&limit=10 HTTP/1.1" 200 422
[2020-05-15 22:19:03,988] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 13328
[2020-05-15 22:19:04,059] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /statistic/admin/ HTTP/1.1" 200 3937
[2020-05-15 22:19:04,086] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /manufacturer/view/ HTTP/1.1" 200 11027
[2020-05-15 22:19:04,089] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu_user/view/ HTTP/1.1" 200 10316
[2020-05-15 22:19:04,092] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /meter/view/ HTTP/1.1" 200 20643
[2020-05-15 22:19:04,092] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-05-15 22:19:04,094] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/view/ HTTP/1.1" 200 10249
[2020-05-15 22:19:04,094] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu/view/ HTTP/1.1" 200 8912
[2020-05-15 22:19:04,338] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_admin
[2020-05-15 22:19:04,352] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/admin/?action=query_admin&page=1&limit=10 HTTP/1.1" 200 422
[2020-05-15 22:19:04,366] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_manufacturer
[2020-05-15 22:19:04,388] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_dtu_user
[2020-05-15 22:19:04,390] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/manufacturer/?action=query_manufacturer&page=1&limit=10 HTTP/1.1" 200 1235
[2020-05-15 22:19:04,399] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/dtu_user/?action=query_dtu_user&page=1&limit=10 HTTP/1.1" 200 239
[2020-05-15 22:19:04,409] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_dtu
[2020-05-15 22:19:04,411] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_manufacturer
[2020-05-15 22:19:04,412] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_dtu_user_of_select_box
[2020-05-15 22:19:04,436] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/dtu_user/?param=%7B%7D&action=query_dtu_user_of_select_box HTTP/1.1" 200 116
[2020-05-15 22:19:04,441] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/manufacturer/?param=%7B%7D&action=query_manufacturer HTTP/1.1" 200 1235
[2020-05-15 22:19:04,441] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/dtu/?action=query_dtu&page=1&limit=10 HTTP/1.1" 200 1159
[2020-05-15 22:19:04,448] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-05-15 22:19:04,454] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-05-15 22:19:04,457] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_meter
[2020-05-15 22:19:04,474] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_manufacturer
[2020-05-15 22:19:04,477] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/meter/?action=query_meter&page=1&limit=10 HTTP/1.1" 200 1232
[2020-05-15 22:19:04,489] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/manufacturer/?param=%7B%7D&action=query_manufacturer HTTP/1.1" 200 1235
