[2020-03-14 13:22:38,056] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 13:38:24,745] [autoreload.py:203] [autoreload:trigger_reload] [INFO]- D:\project\python\flowmeter\flowmeter\applications\api\auth.py changed, reloading.
[2020-03-14 13:38:25,470] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:07:20,067] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:07:30,948] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 302 0
[2020-03-14 16:07:31,012] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2944
[2020-03-14 16:08:03,928] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2944
[2020-03-14 16:08:13,183] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：login
[2020-03-14 16:08:13,239] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/login/ HTTP/1.1" 200 96
[2020-03-14 16:08:13,298] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/css/modules/layer/default/icon.png HTTP/1.1" 200 11493
[2020-03-14 16:08:14,526] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 8665
[2020-03-14 16:08:14,591] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /welcome/ HTTP/1.1" 200 10977
[2020-03-14 16:08:14,657] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /system/register/ HTTP/1.1" 200 4382
[2020-03-14 16:08:14,673] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /system/frame/ HTTP/1.1" 200 3803
[2020-03-14 16:08:14,693] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/view/ HTTP/1.1" 200 10617
[2020-03-14 16:08:14,719] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu_region/view/ HTTP/1.1" 200 6896
[2020-03-14 16:08:14,734] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu_user/view/ HTTP/1.1" 200 10678
[2020-03-14 16:08:14,756] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /manufacturer/view/ HTTP/1.1" 200 11393
[2020-03-14 16:08:14,787] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /meter/view/ HTTP/1.1" 200 12560
[2020-03-14 16:08:14,800] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu/view/ HTTP/1.1" 200 9053
[2020-03-14 16:08:14,831] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:08:14,995] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/system/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:08:15,000] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/system/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:08:15,005] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/dtu_user/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:08:15,009] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/admin/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:08:15,010] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/manufacturer/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:08:15,015] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/dtu_region/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:08:15,016] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/system/?action=query_data_field&page=1&limit=10 HTTP/1.1" 500 18945
[2020-03-14 16:08:15,016] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/system/?action=query_control_register&page=1&limit=10 HTTP/1.1" 500 18966
[2020-03-14 16:08:15,017] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/dtu_user/?action=query_dtu_user&page=1&limit=10 HTTP/1.1" 500 18948
[2020-03-14 16:08:15,018] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/admin/?action=query_admin&page=1&limit=10 HTTP/1.1" 500 18924
[2020-03-14 16:08:15,021] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/manufacturer/?action=query_manufacturer&page=1&limit=10 HTTP/1.1" 500 18980
[2020-03-14 16:08:15,022] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/dtu_region/?action=query_dtu_region&page=1&limit=10 HTTP/1.1" 500 18964
[2020-03-14 16:08:15,058] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/auth/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:08:15,064] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/dtu_user/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:08:15,069] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/meter/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:08:15,075] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/dtu/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:08:15,080] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 500 18916
[2020-03-14 16:08:15,080] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/manufacturer/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:08:15,081] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/dtu_user/?param=%7B%7D&action=query_dtu_user HTTP/1.1" 500 18926
[2020-03-14 16:08:15,081] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/meter/?action=query_meter&page=1&limit=10 HTTP/1.1" 500 18924
[2020-03-14 16:08:15,082] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/dtu/?action=query_dtu&page=1&limit=10 HTTP/1.1" 500 18908
[2020-03-14 16:08:15,083] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/manufacturer/?param=%7B%7D&action=query_manufacturer HTTP/1.1" 500 18956
[2020-03-14 16:08:15,101] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/manufacturer/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:08:15,102] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/manufacturer/?param=%7B%7D&action=query_manufacturer HTTP/1.1" 500 18954
[2020-03-14 16:10:11,976] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:10:17,741] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 8665
[2020-03-14 16:10:17,805] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /welcome/ HTTP/1.1" 200 10977
[2020-03-14 16:10:17,873] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /system/register/ HTTP/1.1" 200 4382
[2020-03-14 16:10:17,882] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /system/frame/ HTTP/1.1" 200 3803
[2020-03-14 16:10:17,891] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/view/ HTTP/1.1" 200 10617
[2020-03-14 16:10:17,893] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu_region/view/ HTTP/1.1" 200 6896
[2020-03-14 16:10:17,900] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu_user/view/ HTTP/1.1" 200 10678
[2020-03-14 16:10:17,904] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /manufacturer/view/ HTTP/1.1" 200 11393
[2020-03-14 16:10:17,909] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu/view/ HTTP/1.1" 200 9053
[2020-03-14 16:10:17,913] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /meter/view/ HTTP/1.1" 200 12560
[2020-03-14 16:10:17,916] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:10:18,244] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/system/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:10:18,245] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/admin/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:10:18,245] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/system/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:10:18,256] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/system/?action=query_data_field&page=1&limit=10 HTTP/1.1" 500 18945
[2020-03-14 16:10:18,262] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/dtu_user/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:10:18,263] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/admin/?action=query_admin&page=1&limit=10 HTTP/1.1" 500 18924
[2020-03-14 16:10:18,265] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/system/?action=query_control_register&page=1&limit=10 HTTP/1.1" 500 18966
[2020-03-14 16:10:18,277] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/dtu_user/?action=query_dtu_user&page=1&limit=10 HTTP/1.1" 500 18948
[2020-03-14 16:10:18,286] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/manufacturer/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:10:18,293] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/dtu_region/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:10:18,298] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/manufacturer/?action=query_manufacturer&page=1&limit=10 HTTP/1.1" 500 18980
[2020-03-14 16:10:18,307] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/dtu_region/?action=query_dtu_region&page=1&limit=10 HTTP/1.1" 500 18964
[2020-03-14 16:10:18,314] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/auth/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:10:18,322] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 500 18916
[2020-03-14 16:10:18,332] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/manufacturer/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:10:18,337] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/dtu/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:10:18,343] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/dtu_user/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:10:18,344] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/manufacturer/?param=%7B%7D&action=query_manufacturer HTTP/1.1" 500 18954
[2020-03-14 16:10:18,345] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/dtu/?action=query_dtu&page=1&limit=10 HTTP/1.1" 500 18908
[2020-03-14 16:10:18,350] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/meter/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:10:18,351] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/dtu_user/?param=%7B%7D&action=query_dtu_user HTTP/1.1" 500 18926
[2020-03-14 16:10:18,357] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/meter/?action=query_meter&page=1&limit=10 HTTP/1.1" 500 18924
[2020-03-14 16:10:18,366] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/manufacturer/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:10:18,367] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/manufacturer/?param=%7B%7D&action=query_manufacturer HTTP/1.1" 500 18956
[2020-03-14 16:10:27,388] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:10:53,263] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:11:33,955] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 8665
[2020-03-14 16:11:34,000] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /welcome/ HTTP/1.1" 200 10977
[2020-03-14 16:11:34,071] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /system/register/ HTTP/1.1" 200 4382
[2020-03-14 16:11:34,073] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /system/frame/ HTTP/1.1" 200 3803
[2020-03-14 16:11:34,079] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/view/ HTTP/1.1" 200 10617
[2020-03-14 16:11:34,083] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu_region/view/ HTTP/1.1" 200 6896
[2020-03-14 16:11:34,087] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu_user/view/ HTTP/1.1" 200 10678
[2020-03-14 16:11:34,091] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /manufacturer/view/ HTTP/1.1" 200 11393
[2020-03-14 16:11:34,095] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu/view/ HTTP/1.1" 200 9053
[2020-03-14 16:11:34,099] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /meter/view/ HTTP/1.1" 200 12560
[2020-03-14 16:11:34,101] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:11:34,367] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/system/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:11:34,368] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/system/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:11:34,376] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/system/?action=query_control_register&page=1&limit=10 HTTP/1.1" 500 18966
[2020-03-14 16:11:34,378] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/system/?action=query_data_field&page=1&limit=10 HTTP/1.1" 500 18945
[2020-03-14 16:11:34,397] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/admin/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:11:34,405] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/dtu_user/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:11:34,406] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/admin/?action=query_admin&page=1&limit=10 HTTP/1.1" 500 18924
[2020-03-14 16:11:34,413] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/dtu_region/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:11:34,414] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/dtu_user/?action=query_dtu_user&page=1&limit=10 HTTP/1.1" 500 18948
[2020-03-14 16:11:34,416] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/dtu_region/?action=query_dtu_region&page=1&limit=10 HTTP/1.1" 500 18964
[2020-03-14 16:11:34,457] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/manufacturer/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:11:34,469] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/auth/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:11:34,470] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/dtu/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:11:34,470] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/manufacturer/?action=query_manufacturer&page=1&limit=10 HTTP/1.1" 500 18980
[2020-03-14 16:11:34,476] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/manufacturer/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:11:34,487] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 500 18916
[2020-03-14 16:11:34,487] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/meter/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:11:34,488] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/dtu_user/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:11:34,489] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/dtu/?action=query_dtu&page=1&limit=10 HTTP/1.1" 500 18908
[2020-03-14 16:11:34,490] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/manufacturer/?param=%7B%7D&action=query_manufacturer HTTP/1.1" 500 18954
[2020-03-14 16:11:34,490] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/meter/?action=query_meter&page=1&limit=10 HTTP/1.1" 500 18924
[2020-03-14 16:11:34,494] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/dtu_user/?param=%7B%7D&action=query_dtu_user HTTP/1.1" 500 18926
[2020-03-14 16:11:34,506] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /handler/manufacturer/
Traceback (most recent call last):
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\project\python\flowmeter\venv\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "D:\project\python\flowmeter\flowmeter\middlewares\auth.py", line 76, in process_request
    if is_action_allowed(request, action) is False:
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 37, in is_action_allowed
    if __check_role_version_expire(user):
  File "D:\project\python\flowmeter\flowmeter\applications\api\auth.py", line 22, in __check_role_version_expire
    if user['role_version'] < now_version:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2020-03-14 16:11:34,507] [basehttp.py:154] [basehttp:log_message] [ERROR]- "GET /handler/manufacturer/?param=%7B%7D&action=query_manufacturer HTTP/1.1" 500 18956
[2020-03-14 16:13:22,350] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:16:30,271] [autoreload.py:203] [autoreload:trigger_reload] [INFO]- D:\project\python\flowmeter\flowmeter\config\api\cache.py changed, reloading.
[2020-03-14 16:16:31,006] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:17:46,162] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:18:05,752] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:18:22,517] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 302 0
[2020-03-14 16:18:22,526] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2944
[2020-03-14 16:18:25,622] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：login
[2020-03-14 16:18:25,630] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/login/ HTTP/1.1" 200 96
[2020-03-14 16:18:26,885] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 8665
[2020-03-14 16:18:26,915] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /welcome/ HTTP/1.1" 200 10977
[2020-03-14 16:18:26,961] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /system/register/ HTTP/1.1" 200 4382
[2020-03-14 16:18:26,963] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /system/frame/ HTTP/1.1" 200 3803
[2020-03-14 16:18:26,966] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/view/ HTTP/1.1" 200 10617
[2020-03-14 16:18:26,972] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu_region/view/ HTTP/1.1" 200 6896
[2020-03-14 16:18:26,973] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu_user/view/ HTTP/1.1" 200 10678
[2020-03-14 16:18:26,977] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /manufacturer/view/ HTTP/1.1" 200 11393
[2020-03-14 16:18:26,981] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu/view/ HTTP/1.1" 200 9053
[2020-03-14 16:18:26,985] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /meter/view/ HTTP/1.1" 200 12560
[2020-03-14 16:18:26,986] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:18:27,232] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_data_field
[2020-03-14 16:18:27,235] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/system/?action=query_data_field&page=1&limit=10 HTTP/1.1" 200 1555
[2020-03-14 16:18:27,244] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_manufacturer
[2020-03-14 16:18:27,271] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_admin
[2020-03-14 16:18:27,277] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/manufacturer/?action=query_manufacturer&page=1&limit=10 HTTP/1.1" 200 1235
[2020-03-14 16:18:27,278] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_control_register
[2020-03-14 16:18:27,285] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/system/?action=query_control_register&page=1&limit=10 HTTP/1.1" 200 1017
[2020-03-14 16:18:27,285] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/admin/?action=query_admin&page=1&limit=10 HTTP/1.1" 200 417
[2020-03-14 16:18:27,285] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_dtu_user
[2020-03-14 16:18:27,292] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/dtu_user/?action=query_dtu_user&page=1&limit=10 HTTP/1.1" 200 239
[2020-03-14 16:18:27,299] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:18:27,301] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:18:27,320] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_dtu_region
[2020-03-14 16:18:27,337] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_meter
[2020-03-14 16:18:27,341] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_manufacturer
[2020-03-14 16:18:27,363] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_dtu
[2020-03-14 16:18:27,367] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/meter/?action=query_meter&page=1&limit=10 HTTP/1.1" 200 464
[2020-03-14 16:18:27,367] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_dtu_user
[2020-03-14 16:18:27,372] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/dtu_region/?action=query_dtu_region&page=1&limit=10 HTTP/1.1" 200 337
[2020-03-14 16:18:27,387] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/dtu_user/?param=%7B%7D&action=query_dtu_user HTTP/1.1" 200 239
[2020-03-14 16:18:27,389] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/dtu/?action=query_dtu&page=1&limit=10 HTTP/1.1" 200 708
[2020-03-14 16:18:27,390] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/manufacturer/?param=%7B%7D&action=query_manufacturer HTTP/1.1" 200 1235
[2020-03-14 16:18:27,397] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_manufacturer
[2020-03-14 16:18:27,414] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/manufacturer/?param=%7B%7D&action=query_manufacturer HTTP/1.1" 200 1235
[2020-03-14 16:18:28,793] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /static/lib/layui/css/modules/layer/default/loading-1.gif HTTP/1.1" 200 701
[2020-03-14 16:18:28,833] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=dtu_user HTTP/1.1" 200 29151
[2020-03-14 16:18:31,373] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30345
[2020-03-14 16:18:33,777] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30345
[2020-03-14 16:18:36,874] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30345
[2020-03-14 16:19:50,805] [autoreload.py:203] [autoreload:trigger_reload] [INFO]- D:\project\python\flowmeter\flowmeter\init.py changed, reloading.
[2020-03-14 16:19:51,543] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:19:53,349] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=dtu_user HTTP/1.1" 200 29151
[2020-03-14 16:19:55,269] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=dtu_user HTTP/1.1" 200 29151
[2020-03-14 16:19:57,912] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=dtu_user HTTP/1.1" 200 29151
[2020-03-14 16:20:32,124] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30273
[2020-03-14 16:20:35,464] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:20:35,544] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:20:36,625] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:20:36,693] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:20:36,695] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:20:38,708] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:20:38,757] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:20:38,759] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:35:15,703] [autoreload.py:203] [autoreload:trigger_reload] [INFO]- D:\project\python\flowmeter\flowmeter\applications\api\auth.py changed, reloading.
[2020-03-14 16:35:16,423] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:35:17,959] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 302 0
[2020-03-14 16:35:17,970] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2944
[2020-03-14 16:35:21,280] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 302 0
[2020-03-14 16:35:21,285] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2944
[2020-03-14 16:35:23,561] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 302 0
[2020-03-14 16:35:23,570] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2944
[2020-03-14 16:35:36,717] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：login
[2020-03-14 16:35:36,724] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/login/ HTTP/1.1" 200 96
[2020-03-14 16:35:37,991] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /index/ HTTP/1.1" 200 8665
[2020-03-14 16:35:38,028] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /welcome/ HTTP/1.1" 200 10977
[2020-03-14 16:35:38,095] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /system/register/ HTTP/1.1" 200 4382
[2020-03-14 16:35:38,101] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /system/frame/ HTTP/1.1" 200 3803
[2020-03-14 16:35:38,108] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /admin/view/ HTTP/1.1" 200 10617
[2020-03-14 16:35:38,114] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu_region/view/ HTTP/1.1" 200 6896
[2020-03-14 16:35:38,120] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu_user/view/ HTTP/1.1" 200 10678
[2020-03-14 16:35:38,126] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /manufacturer/view/ HTTP/1.1" 200 11393
[2020-03-14 16:35:38,132] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /dtu/view/ HTTP/1.1" 200 9053
[2020-03-14 16:35:38,138] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /meter/view/ HTTP/1.1" 200 12560
[2020-03-14 16:35:38,144] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:35:38,371] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_control_register
[2020-03-14 16:35:38,373] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/system/?action=query_control_register&page=1&limit=10 HTTP/1.1" 200 1017
[2020-03-14 16:35:38,382] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_admin
[2020-03-14 16:35:38,389] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/admin/?action=query_admin&page=1&limit=10 HTTP/1.1" 200 417
[2020-03-14 16:35:38,397] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_data_field
[2020-03-14 16:35:38,402] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/system/?action=query_data_field&page=1&limit=10 HTTP/1.1" 200 1555
[2020-03-14 16:35:38,405] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_dtu_user
[2020-03-14 16:35:38,412] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/dtu_user/?action=query_dtu_user&page=1&limit=10 HTTP/1.1" 200 239
[2020-03-14 16:35:38,414] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_manufacturer
[2020-03-14 16:35:38,430] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/manufacturer/?action=query_manufacturer&page=1&limit=10 HTTP/1.1" 200 1235
[2020-03-14 16:35:38,456] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_dtu_region
[2020-03-14 16:35:38,467] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:35:38,481] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:35:38,483] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_dtu
[2020-03-14 16:35:38,483] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_dtu_user
[2020-03-14 16:35:38,488] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_manufacturer
[2020-03-14 16:35:38,491] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_meter
[2020-03-14 16:35:38,506] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/dtu_user/?param=%7B%7D&action=query_dtu_user HTTP/1.1" 200 239
[2020-03-14 16:35:38,509] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/dtu_region/?action=query_dtu_region&page=1&limit=10 HTTP/1.1" 200 337
[2020-03-14 16:35:38,516] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/meter/?action=query_meter&page=1&limit=10 HTTP/1.1" 200 464
[2020-03-14 16:35:38,517] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/dtu/?action=query_dtu&page=1&limit=10 HTTP/1.1" 200 708
[2020-03-14 16:35:38,523] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/manufacturer/?param=%7B%7D&action=query_manufacturer HTTP/1.1" 200 1235
[2020-03-14 16:35:38,527] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_manufacturer
[2020-03-14 16:35:38,542] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/manufacturer/?param=%7B%7D&action=query_manufacturer HTTP/1.1" 200 1235
[2020-03-14 16:35:40,039] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=dtu_user HTTP/1.1" 200 29223
[2020-03-14 16:35:42,466] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30372
[2020-03-14 16:35:44,901] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:35:44,977] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:35:46,135] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:35:46,197] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:35:46,200] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:35:51,290] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=manufacturer HTTP/1.1" 200 29231
[2020-03-14 16:35:54,106] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30273
[2020-03-14 16:35:56,157] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:35:56,247] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:35:57,081] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:35:57,149] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:35:57,151] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:36:03,652] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30372
[2020-03-14 16:36:04,761] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:36:04,841] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:36:06,154] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:36:06,221] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:36:06,224] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:36:53,888] [autoreload.py:203] [autoreload:trigger_reload] [INFO]- D:\project\python\flowmeter\flowmeter\applications\core\auth.py changed, reloading.
[2020-03-14 16:36:54,595] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:36:56,021] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30372
[2020-03-14 16:36:57,662] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:36:57,741] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:36:58,821] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:36:58,888] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:36:58,891] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:37:58,049] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:38:02,478] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30273
[2020-03-14 16:38:03,420] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:38:03,497] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:38:04,269] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:38:04,337] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:38:04,340] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:38:15,050] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:38:20,152] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30273
[2020-03-14 16:38:21,182] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:38:21,272] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:38:22,043] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:38:22,115] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:38:22,117] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:39:16,836] [autoreload.py:203] [autoreload:trigger_reload] [INFO]- D:\project\python\flowmeter\flowmeter\applications\core\auth.py changed, reloading.
[2020-03-14 16:39:17,554] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:39:18,535] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30273
[2020-03-14 16:39:19,943] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:39:20,026] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:39:20,767] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:39:20,832] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:39:20,834] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:39:46,971] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:39:52,211] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30372
[2020-03-14 16:39:52,993] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:39:53,083] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:39:53,922] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:39:53,997] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:39:54,000] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:39:54,941] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30372
[2020-03-14 16:40:33,377] [autoreload.py:203] [autoreload:trigger_reload] [INFO]- D:\project\python\flowmeter\flowmeter\applications\core\auth.py changed, reloading.
[2020-03-14 16:40:34,197] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-03-14 16:40:35,374] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30162
[2020-03-14 16:40:36,970] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:40:36,973] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:40:36,984] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:40:37,058] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:40:37,061] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:40:38,404] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30162
[2020-03-14 16:40:39,223] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:40:39,227] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:40:39,236] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:40:39,290] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:40:39,292] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:40:44,284] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30162
[2020-03-14 16:40:45,098] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:40:45,101] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:40:45,110] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:40:45,172] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:40:45,174] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:40:52,563] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30162
[2020-03-14 16:40:53,405] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:40:53,409] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:40:53,420] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:40:53,481] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:40:53,483] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:40:54,300] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30162
[2020-03-14 16:40:56,558] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:40:56,629] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:40:56,638] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:40:56,720] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:40:56,722] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:41:01,783] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/auth/view/?name=admin HTTP/1.1" 200 30063
[2020-03-14 16:41:03,401] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：edit_role_auth
[2020-03-14 16:41:03,478] [basehttp.py:154] [basehttp:log_message] [INFO]- "POST /handler/auth/ HTTP/1.1" 200 68
[2020-03-14 16:41:03,488] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /role/view/ HTTP/1.1" 200 4075
[2020-03-14 16:41:03,546] [common.py:63] [common:get_action_handler] [INFO]- 当前正在操作action：query_role
[2020-03-14 16:41:03,549] [basehttp.py:154] [basehttp:log_message] [INFO]- "GET /handler/auth/?action=query_role&page=1&limit=10 HTTP/1.1" 200 294
[2020-03-14 16:42:50,417] [autoreload.py:203] [autoreload:trigger_reload] [INFO]- D:\project\python\flowmeter\flowmeter\settings.py changed, reloading.
[2020-03-14 16:42:51,118] [autoreload.py:578] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
